// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.5.1
//
// Generated by DffGenerator (Version 0.74.7)
// Generated from Engine.dff
//
// AUTO-GENERATED FILE. DO NOT MODIFY.
package com.example.figmatest.protocol;

import com.example.figmatest.imt.base.core.serialization.Deserializer;
import com.example.figmatest.imt.base.core.serialization.SerializableIfc;
import com.example.figmatest.imt.base.core.serialization.Serializer;
import java.util.Objects;

public final class EngineSettingsProtocol implements SerializableIfc {
    PatientSettingsProtocol patientSettings;

    /**
     * Constructor.
     */
    public EngineSettingsProtocol(PatientSettingsProtocol patientSettings) {
        this.patientSettings = patientSettings;
    }

    public EngineSettingsProtocol(Deserializer deserializer) {
        this.patientSettings = new PatientSettingsProtocol.Builder().build();
        deserialize(deserializer);
    }

    @Override
    public int getMaxSerializedSize() {
        return 171;
    }

    @Override
    public void deserialize(Deserializer deserializer) {
        patientSettings.deserialize(deserializer);
    }

    @Override
    public void serialize(Serializer serializer) {
        patientSettings.serialize(serializer);
    }

    @Override
    public EngineSettingsProtocol deepClone() {
        return new EngineSettingsProtocol(
                patientSettings.deepClone());
    }

    public PatientSettingsProtocol getPatientSettings() {
        return patientSettings;
    }

    @Override
    public boolean equals(Object obj) {
        if ((obj == null) || !(obj instanceof EngineSettingsProtocol)) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        final EngineSettingsProtocol other = (EngineSettingsProtocol) obj;
        return this.patientSettings.equals(other.patientSettings);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.patientSettings
        );
    }

    public static EngineSettingsProtocol.Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private EngineSettingsProtocol protocol;
        private PatientSettingsProtocol patientSettings;

        public Builder() {
        }

        /**
         * Constructor.
         */
        public Builder(EngineSettingsProtocol protocol) {
            if (protocol == null) {
                return;
            }
            this.patientSettings = protocol.patientSettings.deepClone();
        }

        /**
         * Sets current values from existing protocol.
         */
        public void set(EngineSettingsProtocol protocol) {
            if (protocol == null) {
                return;
            }
            this.patientSettings = protocol.patientSettings.deepClone();
        }

        public EngineSettingsProtocol.Builder patientSettings(PatientSettingsProtocol patientSettings) {
            this.patientSettings = patientSettings;
            return this;
        }

        /**
         * Builds the EngineSettingsProtocol object.
         */
        public EngineSettingsProtocol build() {
            if (patientSettings == null) {
                patientSettings = new PatientSettingsProtocol.Builder().build();
            }
            protocol = new EngineSettingsProtocol(
                    patientSettings);
            return protocol;
        }

        /**
         * Builds or updates the EngineSettingsProtocol object.
         */
        public EngineSettingsProtocol buildOrUpdate() {
            if (protocol == null) {
                return build();
            }
            protocol.patientSettings = this.patientSettings;
            return protocol;
        }
    }
}
