// (c) IMT - Information Management Technology AG, CH-9470 Buchs, www.imt.ch.
// SW guideline: Technote Coding Guidelines Version. 1.5.1
//
// Generated by DffGenerator (Version 0.74.7)
// Generated from Protocol.dff
//
// AUTO-GENERATED FILE. DO NOT MODIFY.

package com.example.figmatest.protocol;

public class ProtocolIdentifier {
    public static final int MEASUREMENT_DATA = 100;
    public static final int BREATH_BASED_DATA = 101;
    public static final int ENGINEERING_DATA = 102;
    public static final int DEVICE_PARAMETER = 103;
    public static final int MEAS_CTRL_CONFIG = 104;
    public static final int DEVICE_STATUS = 105;
    public static final int DEVICE_DETECTION = 106;
    public static final int SCREEN_CONFIG = 107;
    public static final int PERFORMANCE_DATA = 108;
    public static final int OVERALL_DEVICE_CONFIG = 109;
    public static final int DEVICE_ORIENTATION_STATE = 110;
    public static final int BATTERY_STATE = 111;
    public static final int SD_CARD_AVAILABILITY_STATE = 112;
    public static final int MEASUREMENT_FAST_DATA = 113;
    public static final int MEASUREMENT_SLOW_DATA = 114;
    public static final int MEASUREMENT_CONFIGURATION = 115;
    public static final int CHART_CONFIGURATION = 116;
    public static final int TILES_CONFIGURATION = 117;
    public static final int MEASUREMENT_DATA_SNAPSHOT = 118;
    public static final int PRESSURE_COMPENSATION_NOTIFICATION = 122;
    public static final int CONTEXT_BUTTON = 124;
    public static final int SOFTWARE_UPDATE_COMMAND = 125;
    public static final int FILE_TRANSFER_INIT = 126;
    public static final int FILE_TRANSFER_SUCCESS = 127;
    public static final int FILE_TRANSFER_ERROR = 128;
    public static final int FILE_TRANSFER_PROGRESS = 129;
    public static final int BASEBOARD_REBOOT = 130;
    public static final int BASEBOARD_REBOOTING = 131;
    public static final int BASEBOARD_REBOOTED = 132;
    public static final int REMOTE_FILE_TRANSFER_INIT = 133;
    public static final int REMOTE_FILE_TRANSFER_BLOCK = 134;
    public static final int REMOTE_FILE_TRANSFER_RESPONSE = 135;
    public static final int REMOTE_FILE_TRANSFER_PROGRESS = 136;
    public static final int STATISTICS_CONTROL = 137;
    public static final int DEV_VALUES_ENABLE_CHANGED = 138;
    public static final int PROFILE = 139;
    public static final int SYSTEM_CONFIG = 140;
    public static final int PRODUCTION_DEVICE_PARAMETER = 141;
    public static final int PRODUCTION_CALIBRATION_MODE = 142;
    public static final int PROFILE_FEEDBACK = 143;
    public static final int NEW_BREATH_STARTED = 144;
    public static final int CALIBRATION_ALERT = 146;
    public static final int ETHERNET_STATE = 147;
    public static final int ETHERNET_COMMAND = 148;
    public static final int LOCK_MODE = 149;
    public static final int MEASUREMENT_DATA_SNAPSHOT_STATE = 151;
    public static final int MEASUREMENT_DATA_SNAPSHOT_COMMAND = 152;
    public static final int USB_MASS_STORAGE_STATE = 153;
    public static final int USB_MASS_STORAGE_COMMAND = 154;
    public static final int ZERO_CALIBRATION = 155;
    public static final int OXYGEN_CALIBRATION = 157;
    public static final int SOFTWARE_UPDATE_STATE = 159;
    public static final int INTERNET_DOWNLOAD_COMMAND = 160;
    public static final int INTERNET_DOWNLOAD_STATE = 161;
    public static final int INTERNET_SOFTWARE_UPDATE_COMMAND = 162;
    public static final int INTERNET_SOFTWARE_UPDATE_STATE = 163;
    public static final int USB_FILE_COMMAND = 164;
    public static final int USB_FILE_NOTIFICATION = 165;
    public static final int AUXILIARY_CONFIG = 166;
    public static final int RESET_BREATH_DATA = 167;
    public static final int FLOAT_STATS = 168;
    public static final int INT_STATS = 169;
    public static final int UINT_STATS = 170;
    public static final int BUZZER = 171;
    public static final int DEVICE_RESTART = 172;
    public static final int APPS_CONFIGURATION = 173;
    public static final int RECORDING_SETTING = 174;
    public static final int RECORDING_STATISTICS = 175;
    public static final int RECORDING_PARAMETERS = 176;
    public static final int RECORDING_COMMAND = 177;
    public static final int RECORDING_FINISH = 178;
    public static final int OXYGEN_SENSOR_WARNING = 179;
    public static final int FLOW_DIRECTION_WARNING = 180;
    public static final int MEASUREMENT_IRMA_DATA = 181;
    public static final int COMMAND_IRMA_DATA = 182;
    public static final int STATUS_IRMA_DATA = 183;
    public static final int ACKNOLEDGE = 184;
    public static final int DEVICE_SETTINGS = 185;
    public static final int MEASUREMENT_SETTINGS = 186;
    public static final int TRIGGER_SETTINGS = 187;
    public static final int DBP_LED_CONTROL = 188;
    public static final int DBP_BUTTON_STATE = 189;
    public static final int BOOTLOADER_STATUS = 190;
    public static final int BOOTLOADER_COMMAND = 191;
    public static final int DBP_LED_STATE = 192;
    public static final int CALBENCH_MODE = 193;
    public static final int PERSISTANCE_STATUS = 194;
    public static final int SNAPSHOT_INFO_DATA = 195;
    public static final int PRODUCTION_TEST = 196;
    public static final int CURVE_TRIGGER_CONFIGURATION = 197;
    public static final int VITAL_SIGNS_DATA = 2002;
    public static final int ENGINE_SETTINGS = 2005;
    public static final int ENGINE_COMMAND = 2006;
    public static final int PATIENT_SETTINGS = 20016;
}
